/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Block(props) {
  const { nodes, materials } = useGLTF('../../../public/Blocks/Block.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Cube.geometry} material={materials.Material} scale={[0.48, 1, 0.48]}/>
    </group>
  )
}

useGLTF.preload('../../../public/Blocks/Block.glb')